### ISSUE TITLE
Problem with PUBNUB_BUF_MAXLEN

### ISSUE THREAD

**Issue by mattwood2000** [pubnub/samd21#1]
Hi,

I have discovered an issue where changing the PUBNUB_BUF_MAXLEN to a value higher than 263 breaks the subscribe message reception.  There could be other unknown issues as well.

Have a look at the post I published on AVR Freaks for some more details.  Is this a known issue?

http://www.avrfreaks.net/forum/samd21-winc1500-pubnub-issue

Thanks, Matt.

**Comment by MaxPresman** [comment]
Hi @mattwood2000 ,

Thanks for opening an issue. Our Support Team handles SDK issues via our email alias at support@pubnub.com. Please forward the related code snippet with the configuration and stack trace you are experiencing.
